title: Fashion Encyclopedia - всё о моде и стиле
email: ellaksenofontova@gmail.com
description: >-
  Блог о моде и стиле
baseurl: ""
url: ""
github_username:  Ella-Ksenofontova

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.txt"

lang: ru-RU

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

sass:
  sass_dir: _sass
  load_paths:
        - _sass
        - node_modules

paginate: 12

encoding: utf-8

timezone: Europe/Moscow

defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values: 
      layout: post
      title: ""
      author: "Элла Ксенофонтова"

collections:
  site_categories:
    output: true
    permalink: categories/:name/

domain: ella-ksenofontova.github.io 
url: https://ella-ksenofontova.github.io  
baseurl: /fashion-encyclopedia